# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:3.1.2"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mysql:latest

#variables:
#  POSTGRES_DB: database_name

# Cache gems in between builds
#cache:
#  paths:
#    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v # Print out ruby version for debugging
  # Uncomment next line if your rails app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install

# Optional - Delete if not using `rubocop`
rubocop:
  script:
  - rubocop

rspec:
  script:
  - rspec spec

test:
  stage: test
  script:
  - bundle install
  - $(bundle show yaml-lint)/bin/yaml-lint data/
  - bundle exec rspec test.rb
