build:
  environment:
    ruby: '3.2.0'
  nodes:
    analysis:
      tests:
        override:
          - ruby-scrutinizer-run
    tests-with-coverage:
      tests:
        override:
          - command: bundle exec rspec test.rb
            environment:
              'SCRUTINIZER_CC_FILE': 'my-coverage'
            coverage:
              file: 'my-coverage'
              format: 'rb-cc'
filter:
  excluded_paths:
    - coverage/*
    - data/*
    - public/*
