build:
  environment:
    ruby: '2.6.3'
  nodes:
    tests-with-coverage:
      tests:
        override:
          - command: bundle exec rspec test.rb
            environment:
              'SCRUTINIZER_CC_FILE': 'my-coverage'
            coverage:
              file: 'my-coverage'
              format: 'rb-cc'
filter:
  excluded_paths:
    - coverage/*
    - data/*
    - public/*
checks:
    ruby: true