version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.2
        environment:
          BUNDLE_PATH: vendor/bundle
          CC_TEST_REPORTER_ID: 0d489bf5520c78ac08ce9c7925f6c5f477047967bf42ec4fe84fcf2a02be53f4
          TESTOPTS: "--ci-dir=/tmp/test-results"
          APP_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      # YAML Lint
      - type: shell
        name: Check YAML inspector gem
        command: bundle show yaml-lint
      - type: shell
        name: Inspect YAML files with Lint
        command: $(bundle show yaml-lint)/bin/yaml-lint data/
      # Run minitest
      - type: shell
        command: bundle exec rspec test.rb
